// Generated by scripts/engraving-layers.py — do not edit by hand.
// Geometry of the engraved typewriter (?palette=mono) in source px of
// art/typewriter-engraving.png. The page scales it so the roller matches
// the paper's width. The paper goes in at the roller's top edge; the entry
// line (where text appears) is a little higher, at the top of the rod's
// clips, so no text is ever under the machine.

/** Each layer's image (per ink colour, ?ink=sepia|black) and where it sits.
 *  Back to front: back (paper colour behind the carriage), carriage, body,
 *  bell. */
export const ENGRAVING = {
  back: { src: '/art/engraving-back.webp', x: 470, y: 449, w: 743, h: 100 },
  carriage: { src: { sepia: '/art/engraving-carriage-sepia.webp', black: '/art/engraving-carriage-black.webp' }, x: 302, y: 431, w: 987, h: 115 },
  body: { src: { sepia: '/art/engraving-body-sepia.webp', black: '/art/engraving-body-black.webp' }, x: 436, y: 505, w: 794, h: 215 },
  bell: { src: { sepia: '/art/engraving-bell-sepia.webp', black: '/art/engraving-bell-black.webp' }, x: 1162, y: 526, w: 79, h: 59 },
} as const

/** The roller: the paper matches x0–x1 and goes in at its top edge. `line`
 *  is the entry line (the strip's top edge). */
export const ENGRAVING_ROLLER = { x0: 487, x1: 1170, top: 466, line: 449 } as const

/** The bell rings about the foot of its dome. */
export const ENGRAVING_BELL_PIVOT = { x: 1203, y: 582 } as const

/** Where the note's arrow points: the right post (the note sits on the desk
 *  above it), in source px. */
export const ENGRAVING_POST = { x: 1212, top: 431 } as const
