// Generated by scripts/typewriter-layers.py — do not edit by hand.
// Geometry of the raster rig in reference px (art/typewriter-wide.png
// resampled to 1536 px wide). The page scales it so the body matches
// the paper's width.

/** Where each layer image sits in the drawing. */
export const LAYERS = {
  roller: { src: '/art/typewriter-roller.webp', x: 299, y: 222, w: 918, h: 56 },
  body: { src: '/art/typewriter-body.webp', x: 259, y: 216, w: 1012, h: 342 },
  bell: { src: '/art/typewriter-bell.webp', x: 1215, y: 163, w: 59, h: 87 },
  lever: { src: '/art/typewriter-lever.webp', x: 251, y: 158, w: 38, h: 126 },
  axleR: { src: '/art/typewriter-axle-r.webp', x: 1250, y: 250, w: 28, h: 36 },
  knobL: { src: '/art/typewriter-knob-l.webp', x: 219, y: 228, w: 35, h: 88 },
  knobR: { src: '/art/typewriter-knob-r.webp', x: 1275, y: 225, w: 41, h: 105 },
} as const

/** The body: its widest extent (the paper matches it), its top edge (where
 *  the paper disappears: the reveal line), the bottom of the keyboard frame
 *  (desktop shows down to here) and its bottom. */
export const BODY = {
  x0: 259,
  x1: 1263,
  top: 221,
  keyboardBottom: 504,
  bottom: 558,
} as const

/** The roller's window: the notch between the shoulders. The roller layer
 *  is clipped to it (its extensions hide behind the shoulders). */
export const NOTCH = { x0: 383, x1: 1133, y0: 205, y1: 290 } as const

/** Everything drawn, lever to knob, bell top to feet. */
export const MACHINE = { x0: 219, y0: 158, x1: 1316, y1: 558 } as const

/** Pivots: the bell rings about its stem's foot; the knobs turn about
 *  their centres. */
export const BELL_PIVOT = { x: 1240, y: 250 } as const
export const KNOB_L_PIVOT = { x: 236, y: 272 } as const
export const KNOB_R_PIVOT = { x: 1295, y: 277 } as const

/** The plant, a separate drawing (art/plant.png at 1024 px): its whole
 *  box, the pot and the foliage, which sways about the stems' base. */
export const PLANT = { x: 367, y: 133, w: 309, h: 757 } as const
export const PLANT_POT = { src: '/art/plant-pot.webp', x: 370, y: 610, w: 292, h: 280 }
export const PLANT_FOLIAGE = { src: '/art/plant-foliage.webp', x: 367, y: 133, w: 309, h: 526 }
export const STEM_PIVOT = { x: 512, y: 660 } as const
