// Generated by scripts/typewriter-layers.py — do not edit by hand.
// Geometry of the raster rig in the source drawing's px (art/typewriter.png,
// 1024x1024). The page scales it so the roller spans the paper.

/** Where each layer image sits in the source drawing. */
export const LAYERS = {
  body: { src: '/art/typewriter-body.webp', x: 198, y: 284, w: 673, h: 236 },
  carriage: { src: '/art/typewriter-carriage.webp', x: 78, y: 264, w: 829, h: 168 },
  bell: { src: '/art/typewriter-bell.webp', x: 781, y: 209, w: 82, h: 137 },
} as const

/** The roller cylinder: its ends line up with the paper's edges, its top
 *  edge is the platen line (where text comes out). */
export const ROLLER = { x0: 230, x1: 848, top: 308 } as const

/** Where the bell's stem meets the roller: it rings about this point. */
export const BELL_PIVOT = { x: 815, y: 308 } as const

/** The plant, a separate drawing (art/plant.png). */
export const PLANT = { src: '/art/plant.webp', x: 367, y: 133, w: 309, h: 757 }
